# Generated by Django 5.0.1 on 2024-04-07 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True, db_column='date_time')),
                ('deviceName', models.CharField(db_column='device_name', max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meta_data',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('todoName', models.CharField(db_column='todo_name', max_length=255)),
                ('todoDate', models.DateTimeField(auto_now_add=True, db_column='todo_date')),
                ('isCompleted', models.BooleanField(db_column='is_completed', default=False)),
                ('insertAt', models.ForeignKey(db_column='insert_at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_inserts', to='api.metadata')),
                ('updateAt', models.ForeignKey(db_column='update_at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_updates', to='api.metadata')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
