# Generated by Django 5.0.1 on 2024-03-10 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedetails',
            name='deviceId',
            field=models.CharField(db_column='device_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='deviceName',
            field=models.CharField(db_column='device_name', max_length=15),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='lastLoginAt',
            field=models.DateTimeField(db_column='last_login_at'),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='registeredAt',
            field=models.DateTimeField(auto_now_add=True, db_column='registered_at'),
        ),
        migrations.AlterField(
            model_name='devicedetails',
            name='userId',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
