# Generated by Django 5.0.1 on 2024-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_metadata_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isRegular',
            field=models.BooleanField(db_column='is_regular', default=False),
        ),
    ]
