# Generated by Django 5.0.1 on 2024-05-02 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_todo_tododate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stockName', models.CharField(db_column='stock_name', max_length=150)),
                ('stockCode', models.CharField(db_column='stock_code', max_length=50)),
                ('yCode', models.CharField(db_column='yhoo_code', max_length=50)),
                ('isActive', models.BooleanField(db_column='is_active', default=True)),
                ('insertAt', models.ForeignKey(db_column='insert_at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_inserts', to='api.metadata')),
                ('updateAt', models.ForeignKey(db_column='update_at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to='api.metadata')),
            ],
            options={
                'db_table': 'stock_names',
            },
        ),
    ]
