# Generated by Django 5.0.1 on 2024-05-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stocknames'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='date')),
                ('open', models.FloatField(db_column='open')),
                ('close', models.FloatField(db_column='close')),
                ('low', models.FloatField(db_column='low')),
                ('high', models.FloatField(db_column='high')),
                ('adjClode', models.FloatField(db_column='adjClose')),
                ('volume', models.BigIntegerField(db_column='volume')),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_name', to='api.stocknames')),
            ],
            options={
                'db_table': 'trade_data',
            },
        ),
    ]
