# Generated by Django 5.0.1 on 2024-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_adjclode_tradedata_adjclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='ema20',
            field=models.FloatField(db_column='ema20', null=True),
        ),
        migrations.AddField(
            model_name='tradedata',
            name='ema5',
            field=models.FloatField(db_column='ema5', null=True),
        ),
        migrations.AddField(
            model_name='tradedata',
            name='sma50',
            field=models.FloatField(db_column='sma50', null=True),
        ),
    ]
