# Generated by Django 5.0.1 on 2024-05-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tradedata_ema20_tradedata_ema5_tradedata_sma50'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedata',
            name='ema20',
        ),
        migrations.RemoveField(
            model_name='tradedata',
            name='ema5',
        ),
        migrations.RemoveField(
            model_name='tradedata',
            name='sma50',
        ),
    ]
