# Generated by Django 5.0.1 on 2024-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tradedata_ema20_remove_tradedata_ema5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateTimeField()),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
    ]
