# Generated by Django 5.0.1 on 2024-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='endDate',
            field=models.DateTimeField(db_column='end_date', null=True),
        ),
        migrations.AddField(
            model_name='tradedata',
            name='startDate',
            field=models.DateTimeField(db_column='start_date', null=True),
        ),
    ]
