# Generated by Django 5.0.1 on 2024-05-12 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tradedata_prevdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='updated_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
