# Generated by Django 5.0.1 on 2024-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tradedata_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='updatedAt',
            field=models.DateField(auto_now_add=True, db_column='updated_at'),
        ),
    ]
