# Generated by Django 5.0.1 on 2024-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tradedata_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='date',
            field=models.DateField(db_column='date'),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='endDate',
            field=models.DateField(db_column='end_date', null=True),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='prevDate',
            field=models.DateField(db_column='prev_date', null=True),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='startDate',
            field=models.DateField(db_column='start_date', null=True),
        ),
    ]
