# Generated by Django 5.0.1 on 2024-05-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tradedata_date_alter_tradedata_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('startDate', models.DateField(db_column='start_date', null=True)),
                ('endDate', models.DateField(db_column='end_date', null=True)),
                ('ema5', models.FloatField(db_column='ema5', null=True)),
                ('ema20', models.FloatField(db_column='ema20', null=True)),
                ('sma50', models.FloatField(db_column='sma50', null=True)),
                ('updatedAt', models.DateField(auto_now_add=True, db_column='updated_at')),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swing_stock_name', to='api.stocknames')),
            ],
            options={
                'db_table': 'swing_data',
            },
        ),
    ]
