# Generated by Django 5.0.1 on 2024-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_swingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='swingdata',
            name='close',
            field=models.FloatField(db_column='close', null=True),
        ),
    ]
