# Generated by Django 5.0.1 on 2024-05-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_stocknames_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknames',
            name='stockSlug',
            field=models.CharField(db_column='stock_slug', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='StockRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.FloatField(blank=True, null=True)),
                ('m3AvgVol', models.FloatField(blank=True, null=True)),
                ('wpct_4', models.FloatField(blank=True, null=True)),
                ('w52High', models.FloatField(blank=True, null=True)),
                ('w52Low', models.FloatField(blank=True, null=True)),
                ('wpct_52', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('divYield', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('inddy', models.FloatField(blank=True, null=True)),
                ('indpb', models.FloatField(blank=True, null=True)),
                ('indpe', models.FloatField(blank=True, null=True)),
                ('marketCap', models.FloatField(blank=True, null=True)),
                ('mrktCapRank', models.IntegerField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('nShareholders', models.IntegerField(blank=True, null=True)),
                ('lastPrice', models.FloatField(blank=True, null=True)),
                ('ttmPe', models.FloatField(blank=True, null=True)),
                ('marketCapLabel', models.CharField(blank=True, max_length=50, null=True)),
                ('m12Vol', models.FloatField(blank=True, null=True)),
                ('mrktCapf', models.FloatField(blank=True, null=True)),
                ('apef', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('etfLiq', models.FloatField(blank=True, null=True)),
                ('etfLiqLabel', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratio_stock_name', to='api.stocknames')),
            ],
        ),
    ]
