# Generated by Django 5.0.1 on 2024-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_stockratios_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockratios',
            name='away52H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='away52L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='dayChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='isCrossedHigh',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='isCrossedLow',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='monthChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='volumeBreakOut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockratios',
            name='weekChange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
