# Generated by Django 5.0.1 on 2024-05-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_stockratios_away52h_stockratios_away52l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('pmPctT', models.FloatField(blank=True, null=True)),
                ('pmPctP', models.FloatField(blank=True, null=True)),
                ('plPctT', models.FloatField(blank=True, null=True)),
                ('uPlPctT', models.FloatField(blank=True, null=True)),
                ('mfPctT', models.FloatField(blank=True, null=True)),
                ('isPctT', models.FloatField(blank=True, null=True)),
                ('diPctT', models.FloatField(blank=True, null=True)),
                ('othDiPctT', models.FloatField(blank=True, null=True)),
                ('othExInsDiPctT', models.FloatField(blank=True, null=True)),
                ('fiPctT', models.FloatField(blank=True, null=True)),
                ('rhPctT', models.FloatField(blank=True, null=True)),
                ('othPctT', models.FloatField(blank=True, null=True)),
                ('rOthPctT', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holding_stock_name', to='api.stocknames')),
            ],
            options={
                'db_table': 'stock_holdings',
            },
        ),
    ]
