# Generated by Django 5.0.1 on 2024-06-01 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_stockcommentary_stockforecast_stockleverageratios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sw_stock_name', to='api.stocknames')),
            ],
            options={
                'db_table': 'swing_stocks',
            },
        ),
    ]
