# Generated by Django 5.0.1 on 2024-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_swingstocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swingstocks',
            old_name='rank',
            new_name='com_rank',
        ),
        migrations.AddField(
            model_name='swingstocks',
            name='div_rank',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='swingstocks',
            name='hol_rank',
            field=models.FloatField(null=True),
        ),
    ]
