# Generated by Django 5.0.1 on 2024-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_rank_swingstocks_com_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swingstocks',
            name='tot_rank',
            field=models.FloatField(null=True),
        ),
    ]
