# Generated by Django 5.0.1 on 2024-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_trendysector'),
    ]

    operations = [
        migrations.AddField(
            model_name='swingstocks',
            name='fore_rank',
            field=models.FloatField(null=True),
        ),
    ]
