# Generated by Django 5.0.1 on 2024-06-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_swingstocks_fore_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_yr_avg_rtn_inst', models.FloatField(null=True)),
                ('five_yr_hist_rvnu_grth', models.FloatField(null=True)),
                ('one_yr_hist_rvnu_grth', models.FloatField(null=True)),
                ('debt_eqty', models.FloatField(null=True)),
                ('roce', models.FloatField(null=True)),
                ('item', models.CharField(max_length=20, null=True)),
                ('stock', models.ForeignKey(db_column='stock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lg_stock_name', to='api.stocknames')),
            ],
            options={
                'db_table': 'long_stocks',
            },
        ),
    ]
