# Generated by Django 5.0.1 on 2024-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_longstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='longstocks',
            name='away_from',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='longstocks',
            name='five_yr_roe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='longstocks',
            name='pe',
            field=models.FloatField(null=True),
        ),
    ]
